server:
  port: 8201
spring:
  application:
    name: userservice
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
       defaultZone: http://localhost:8101/eureka
management:
  security:
    enabled: false
    roles: USER
  health:
    mail:
      enabled: false
endpoints:
  shutdown:
    enabled: false